#ifndef _API_DEFS_H_
#define _API_DEFS_H_

enum api_functions {
  API_DESTROY_OBJECT = 0x0100,

  API_SYN_SET_VISIBILITY = 0x3F00,
  API_SYN_SET_GLYPH_LOCK,
  API_SYN_RESHAPE_OBJECT_WRT,
  API_SYN_CREATE_REIGON,
  API_SYN_GET_LABEL,
  API_SYN_GET_LABEL_LEN,
  API_SYN_DESTROY_OBJECT,
  API_SYN_CREATE_GROUP,
  API_SYN_CREATE_LIST,

  API_SYN_GET_BUTTON_STATUS,
  API_SYN_SET_BUTTON_STATUS,
  API_SYN_GET_PROGBAR,
  API_SYN_GET_SCROLLBAR_VALUE,
  API_SYN_CHANGE_SLIDER_VALUE,
  API_SYN_GET_SLIDER_VALUE,

  API_END // not a real function...just marks the top (for sanity checking purposes)
};

#endif
